# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 0x0-eventservice-test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: ./front
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        working-directory: ./front
        run: zip -r release.zip .next

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./front/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip -d ./front
        
      - name: Copy .next/static to standalone
        run: cp -r ./front/.next/static ./front/.next/standalone/.next/static
        
      # - name: Set Azure App Service App Settings
      #   uses: Azure/appservice-settings@v1
      #   with:
      #     app-name: '0x0-eventservice-test'
      #     app-settings-json: |
      #       [
      #         { "name": "IS_MAIN_PRODUCT", "value": "false" },
      #         { "name": "API_URL_LOGIN_TEST", "value": "https://0x0-login.azurewebsites.net/api/login?code=9L4lUJuBIQvolKJrqK4EUFKUpvZFevZKRN8DLkhkr-5qAzFucYp7_Q%3D%3D" }
      #       ]
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip -d ./front

      - name: Copy .next/static to standalone
        run: cp -r ./front/.next/static ./front/.next/standalone/.next/static

      - name: Create .env.local from secrets
        run: echo "${{ secrets.ENV_LOCAL_TEST }}" > ./front/.env.local

      - name: Load .env.local
        run: cp ./front/.env.local .env

      - name: Convert .env.local to app-settings-json
        id: env-to-json
        run: |
          cat .env | grep -v '^#' | grep -v '^$' \
          | awk -F= '{gsub(/"/, "\\\"", $2); print "{\"name\":\"" $1 "\", \"value\":\"" $2 "\"}"}' \
          | jq -s '.' > appsettings.json

      - name: Set Azure App Service App Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: '0x0-eventservice-test'
          app-settings-json: ${{ steps.env-to-json.outputs.appsettings }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '0x0-eventservice-test'
          package: ./front/.next/standalone
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60E95571A45D498DBBC22F5A6D23C2B7 }}
